### ISSUE TITLE
integrate carpet plot

### ISSUE THREAD

**Issue by khoffschlag** [pni-lab/PUMI#65]

**Comment by spisakt** [comment]
## We need a new "carpet plot" functionality.

#### This is an example carpet plot:
<img width="849" alt="image" src="https://user-images.githubusercontent.com/21124251/176914769-ebdbd548-ec5b-4e40-997e-257bdc908167.png">

But this is a quite "advanced" case, averages signal in brain atlas regions, before plotting (at plots the regions as well).

First we need a simple version, as the individual-space atlas labels are not always available. (e.g. right after despiking).

The simple version should work like this:
#### INPUT:
- take a 4D functional image as input
- optional argument: 'mask', this can be a 3d binary image (brain mask) or a float between 0 and 1 (default: 0.1), which is a "fractional intensity threshold", i.e. ignoring all voxels being smaller than the `min+mask*(max-min)` (or something like that)
- additional params: ax: matplotlib axis, for composite figure (optional), cmap: matplotlib-like colormap (default: grayscale)

#### The function plots all within-mask voxels as a "carpet image":
 - y axis: voxels (bottom to top along z axis)
 - x axis. timeframes
 - color: voxel intensity
 
#### returns:
the plot itself (matplotlib axis)

The implementation can be largely based on this code:
https://github.com/spisakt/PUMI/blob/master/plot/image.py

But it should be started from scratch, as the example code is too complicated.

--------------------------
#### Wrapper functions for nipype use:

we need a wrapper function, which creates the plot saves it at the current wd and returns it's absolue path: `os.getcwd() + '/' + output_file`, so that it can be easily wrapped into a nipype Function interface.

--------------------------
#### future roadmap: composite plot:
we will extend the functionality later so that the same function can create atlas-based carpet plots and plot additional stuff, like brain plots to visualize atlases, or confounder lineplots below the carpet, etc.
We will open separate issues for that
